### ISSUE TITLE
establish a Code of Conduct

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [NOAA-FIMS/collaborative_workflow#3]
## Problem

No established Code of Conduct for FIMS.

## Potential solution

Reference an established Code of Conduct for the FIMS project.

There are many Codes of Conduct out there and, unless necessary, guidance suggests not writing bespoke codes. [Ethics.org](https://www.ethics.org) lays out why organizations [should have a code of conduct](https://www.ethics.org/resources/free-toolkit/code-of-conduct/), [Open Source Guides](https://opensource.guide/code-of-conduct/) provides links to some examples of Codes of Conduct that are widely used, and [GitHub](https://www.github.com) provides a means to [add a Code of Conduct to your repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project). Some options include

* **[Contributor Covenant 2.1](https://www.contributor-covenant.org/version/2/1/code_of_conduct/)**
* [GitHub Event Code of Conduct](https://github.com/floss-and-code/code_of_conduct)
* [Django](https://www.djangoproject.com/conduct/)
* [Citizen](https://web.archive.org/web/20200330154000/http://citizencodeofconduct.org/)
* [Openscapes](https://www.openscapes.org/code-of-conduct/)

Feel free to edit this comment to include more links.

## Tasks

- [x] ~Talk~ Document ~about~ Codes of Conduct ~at a FIMS meeting to bring everyone up to speed~ 
- [x] Decide on Code of Conduct ~at a FIMS meeting~ (FIMS guidance says just pick one)
- [x] Provide details on how to report violations of the Code of Conduct
- [x] Establish instructions on how to access the Code of Conduct for when new projects start within FIMS

**Comment by kellijohnson-NOAA** [comment]
Suggestion is to use [Contributor Covenant 2.1](https://www.contributor-covenant.org/version/2/1/code_of_conduct/). 👍 if you agree. I will leave this issue open until December 01, 2021; so, please comment before then.

**Comment by cmlegault** [comment]
I find the Contributor Covenant 2.1 too focused on enforcement. Everyone in the project is either a Federal Employee or Contractor, so there are already many enforcement actions available/required if the need arises (which I certainly don't expect).  My preference is for a Code of Conduct that focuses more on expected behavior, such as the Django or [Openscapes](https://www.openscapes.org/code-of-conduct/) ones.

**Comment by kellijohnson-NOAA** [comment]
@cmlegault thanks for the comments. I am wondering if you will feel the same way if you think FIMS 5 years into the future, where development has slowed down and we are thinking about user support and integrating wish list items from power users that are not on the development team? But perhaps we should worry about the best Code of Conduct for right now with the thought that if the need arises we could vote to change at a later date.

**Comment by cmlegault** [comment]
@kellijohnson-NOAA Good point. I had not thought that far down the road to when non-NOAA folks would become part of the team making contributions directly. I'm fine with your original suggestion for the Contributor Covenant 2.1 to address this point. Thanks for thinking further ahead than I did.

**Comment by kellijohnson-NOAA** [comment]
@kristanblackhart-NOAA and @ChristineStawitz-NOAA is there a particular Science and Technology email or other email that we should point people to when they have questions / comments that pertain to topics covered under the Code of Conduct. Much like how FIT has a generic email. But, I am not sure if we want to use the FIT email. I think it is important to have a somewhat neutral party that is willing to provide potentially anonymous information to FIMS leaders when comments are received about the Code of Conduct.

**Comment by kellijohnson-NOAA** [comment]
The last task remaining in this issue is to decide on how to let people know that FIMS and its underlying projects use the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/). Should this be on the FIMS landing page, which doesn't exist yet, and/or in every repository? Also, what do we do about updating the version? Contributor Covenant uses semantic versioning with permanent links. Parties that use the Code are not notified when a new version exists. If every repository has a link to the Code I worry about the links becoming out of sink when we agree to adopt a new version or never looking to see if a new version exists.

**Comment by kellijohnson-NOAA** [comment]
I just found [guidance on how to create community files](https://chromatichq.com/insights/sharing-github-issue-pull-request-templates) so you don't have to put the file in every repository.
